name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.BG_TOKEN }}
      with:
        tag_name: v1.0.0  # Release 的 tag 名称
        release_name: Release v1.0.0  # Release 的名称
        draft: false  # 是否为草稿，这里设为 false
        prerelease: false  # 是否为预发布版本，这里设为 false
    - name: Upload APK to Release 
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.BG_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}  # 使用 create_release 步骤的输出来获取上传 URL
        asset_path: app/build/outputs/apk/release/app-release.apk  # APK 文件的路径
        asset_name: app-release.apk  # 上传后在 Release 页面显示的文件名称
        asset_content_type: application/vnd.android.package-archive  # 文件类型

        release_name: Release v1.0.0  # Release 的名称，你可以根据实际情况修改
        draft: false  # 是否为草稿，这里设为 false
        prerelease: false  # 是否为预发布版本，这里设为 false
